name: WakaTime status update

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: "master"
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
